#  Developed by CQ Inversiones SAS.
#  Copyright ©. 2019 - 2025. All rights reserved.
#  Desarrollado por CQ Inversiones SAS.
#  Copyright ©. 2019 - 2025. Todos los derechos reservados.

# Generated by Django 3.2.11 on 2022-10-05 21:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_zb_organizations', '0024_auto_20221005_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='polygon_file',
            field=models.FileField(blank=True, help_text='upload .shp file', null=True, storage='c:\\Windows\\Temp', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['shp'])], verbose_name='Polygons File'),
        ),
    ]
