from typing import Any
from langchain_core.prompts import PromptTemplate

class PromptManager:
    prompt_module: Any
    def __init__(self, model_module: str) -> None: ...
    @property
    def system_prompt(self) -> str: ...
    def user_prompt(self, i: int | None = None) -> PromptTemplate: ...
    @staticmethod
    def _input_variables(template: str) -> list[str]: ...
