# Generated by Django 5.0.1 on 2024-03-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artd_location", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Created at", verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="status",
            field=models.BooleanField(
                default=True, help_text="Status", verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Updated at", verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Created at", verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="status",
            field=models.BooleanField(
                default=True, help_text="Status", verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Updated at", verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Created at", verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="status",
            field=models.BooleanField(
                default=True, help_text="Status", verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Updated at", verbose_name="Updated at"
            ),
        ),
    ]
