ModName = "MyFirstMod"
ModVersion = "1.0"
ServerSystemName = "MyServerSystem"
ServerSystemCls = "myScript.server.MyServerSystem.MyServerSystem"
ClientSystemName = "MyClientSystem"
ClientSystemCls = "myScript.client.MyClientSystem.MyClientSystem"