#  Developed by CQ Inversiones SAS.
#  Copyright ©. 2019 - 2025. All rights reserved.
#  Desarrollado por CQ Inversiones SAS.
#  Copyright ©. 2019 - 2025. Todos los derechos reservados.

# Generated by Django 3.2.11 on 2022-06-09 19:43

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_zb_organizations', '0012_auto_20220607_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='microsite',
            options={'verbose_name': 'Microsite', 'verbose_name_plural': 'Microsites'},
        ),
        migrations.AlterField(
            model_name='catalog',
            name='micro_site',
            field=models.ForeignKey(help_text='Microsite to which the catalog belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='catalog_micro_site', to='djangocms_zb_organizations.microsite', verbose_name='Microsite owner'),
        ),
        migrations.AlterField(
            model_name='microsite',
            name='abstract',
            field=ckeditor.fields.RichTextField(help_text='Summary to show on the micro site.', max_length=200, verbose_name='Microsite abstract'),
        ),
        migrations.AlterField(
            model_name='microsite',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Content (text) to be displayed on the microsite.', verbose_name='Microsite content'),
        ),
        migrations.AlterField(
            model_name='microsite',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Indicates if the microsite is enabled.', verbose_name='Is enabled'),
        ),
    ]
