#  Developed by CQ Inversiones SAS.
#  Copyright ©. 2019 - 2025. All rights reserved.
#  Desarrollado por CQ Inversiones SAS.
#  Copyright ©. 2019 - 2025. Todos los derechos reservados.

# Generated by Django 3.2.11 on 2022-11-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_zb_filer', '0002_auto_20220609_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=models.TextField(blank=True, db_collation='utf8_general_ci', max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(db_collation='utf8_general_ci', max_length=250, verbose_name='Title'),
        ),
    ]
