PACKAGE_NAME = "langgraph-agentflow"
VERSION = "0.0.1"
DESCRIPTION = "AgentFlow is a Python library that automates the orchestration of multi-step agent workflows by integrating intelligent planning, routing, and execution of specialized operations."
AUTHOR = "Alex Kameni"
AUTHOR_EMAIL = "kamenialexnea@gmail.com"
URL = "https://github.com/KameniAlexNea/langgraph-agentflow"
