# coding: utf-8

"""
    SciCat backend API

    This is the API for the SciCat Backend

    The version of the OpenAPI document: api/v3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scicat_sdk_py.api.origdatablocks_api import OrigdatablocksApi


class TestOrigdatablocksApi(unittest.TestCase):
    """OrigdatablocksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrigdatablocksApi()

    def tearDown(self) -> None:
        pass

    def test_orig_datablocks_controller_create(self) -> None:
        """Test case for orig_datablocks_controller_create

        It creates a new orig datablock for the specified dataset.
        """
        pass

    def test_orig_datablocks_controller_find_all(self) -> None:
        """Test case for orig_datablocks_controller_find_all

        It returns a list of orig datablocks.
        """
        pass

    def test_orig_datablocks_controller_find_by_id(self) -> None:
        """Test case for orig_datablocks_controller_find_by_id

        It retrieve the origdatablock.
        """
        pass

    def test_orig_datablocks_controller_fullfacet(self) -> None:
        """Test case for orig_datablocks_controller_fullfacet

        """
        pass

    def test_orig_datablocks_controller_fullfacet_files(self) -> None:
        """Test case for orig_datablocks_controller_fullfacet_files

        """
        pass

    def test_orig_datablocks_controller_fullquery(self) -> None:
        """Test case for orig_datablocks_controller_fullquery

        """
        pass

    def test_orig_datablocks_controller_fullquery_files(self) -> None:
        """Test case for orig_datablocks_controller_fullquery_files

        """
        pass

    def test_orig_datablocks_controller_is_valid(self) -> None:
        """Test case for orig_datablocks_controller_is_valid

        It validates the orig datablock provided as input.
        """
        pass

    def test_orig_datablocks_controller_remove(self) -> None:
        """Test case for orig_datablocks_controller_remove

        It deletes the origdatablock.
        """
        pass

    def test_orig_datablocks_controller_update(self) -> None:
        """Test case for orig_datablocks_controller_update

        It updates the origdatablock.
        """
        pass


if __name__ == '__main__':
    unittest.main()
