# Generated by Django 5.1.6 on 2025-04-04 05:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_testmodelrelated_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodelrelated',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
