# questionnaire_questions = [
# 	"You regularly make new friends. ",
# 	"You find the idea of networking or promoting yourself to strangers very daunting. ",
# 	"You feel comfortable just walking up to someone you find interesting and striking up a conversation. ",
# 	"You enjoy participating in team-based activities. ",
# 	"You enjoy solitary hobbies or activities more than group ones. ",
# 	"You usually wait for others to introduce themselves first at social gatherings. ",
# 	"You usually prefer to be around others rather than on your own. ",
# 	"You can easily connect with people you have just met. ",
# 	"You avoid making phone calls. ",
# 	"You would love a job that requires you to work alone most of the time. ",
# 	"Complex and novel ideas excite you more than simple and straightforward ones. ",
# 	"You are not too interested in discussions about various interpretations of creative works. ",
# 	"You enjoy experimenting with new and untested approaches. ",
# 	"You cannot imagine yourself writing fictional stories for a living. ",
# 	"You are drawn to various forms of creative expression, such as writing. ",
# 	"You enjoy exploring unfamiliar ideas and viewpoints. ",
# 	"You believe that pondering abstract philosophical questions is a waste of time. ",
# 	"You are not too interested in discussing theories on what the world could look like in the future. ",
# 	"You actively seek out new experiences and knowledge areas to explore. ",
# 	"You complete things methodically without skipping over any steps. ",
# 	"You usually feel more persuaded by what resonates emotionally with you than by factual arguments. ",
# 	"People’s stories and emotions speak louder to you than numbers or data. ",
# 	"You prioritize facts over people’s feelings when determining a course of action. ",
# 	"You prioritize being sensitive over being completely honest. ",
# 	"You favor efficiency in decisions, even if it means disregarding some emotional aspects. ",
# 	"In disagreements, you prioritize proving your point over preserving the feelings of others. ",
# 	"Your mood can change very quickly. ",
# 	"When facts and feelings conflict, you usually find yourself following your heart. ",
# 	"You are not easily swayed by emotional arguments. ",
# 	"You usually base your choices on objective facts rather than emotional impressions. ",
# 	"Your living and working spaces are clean and organized. ",
# 	"You prioritize and plan tasks effectively, often completing them well before the deadline. ",
# 	"You like to use organizing tools like schedules and lists. ",
# 	"You often allow the day to unfold without any schedule at all. ",
# 	"You prefer to do your chores before allowing yourself to relax. ",
# 	"You often end up doing things at the last possible moment. ",
# 	"You find it challenging to maintain a consistent work or study schedule. ",
# 	"You like to have a to-do list for each day. ",
# 	"If your plans are interrupted, your top priority is to get back on track as soon as possible. ",
# 	"Your personal work style is closer to spontaneous bursts of energy than organized and consistent efforts. ",
# 	"Do you often find yourself changing your opinion based on who you're talking to?",
# 	"Are you comfortable disagreeing with someone, even if they are a close friend or authority figure?",
# 	"When making decisions, do you prioritize the perspectives of others over your own thoughts?",
# 	"Do you feel pressure to conform to group norms, even if they don't align with your personal beliefs?",
# 	"Do you often second-guess your choices after hearing someone else's opinion?",
# 	"Do you worry about being judged by others if you express a different viewpoint?",
# 	"Would you describe yourself as a people pleaser, often prioritizing others' needs over your own?",
# 	"In a group discussion, are you more likely to adapt to the majority view?",
# 	"Do you stand firm on your decisions that are well researched, even when faced with strong opposition?",
# ]
#
# OPENNESS_INCIDIES = [40, 41, 42, 43, 44, 45, 46, 47, 48]

questionnaire_questions = [
	"Do you often find yourself changing your opinion based on who you're talking to?",
	"Are you comfortable disagreeing with someone, even if they are a close friend or authority figure?",
	"When making decisions, do you prioritize the perspectives of others over your own thoughts?",
	"Do you feel pressure to conform to group norms, even if they don't align with your personal beliefs?",
	"Do you often second-guess your choices after hearing someone else's opinion?",
	"Do you worry about being judged by others if you express a different viewpoint?",
	"Would you describe yourself as a people pleaser, often prioritizing others' needs over your own?",
	"In a group discussion, are you more likely to adapt to the majority view?",
	"Do you stand firm on your decisions that are well researched, even when faced with strong opposition?",
]

OPENNESS_INCIDIES = [i for i in range(9)]

